---
- name: Bash | Ensure .config directory exists
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config"
    state: directory
    owner: "{{ whoami }}"
    group: "{{ whoami }}"
    mode: 0755

- name: Bash | Copy .bashrc
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/roles/bash/files/.bashrc"
    dest: "{{ ansible_env.HOME }}/.bashrc"
    owner: "{{ whoami }}"
    group: "{{ whoami }}"
    mode: 0644
