---

- name: Zsh | Run Task/s
  ansible.builtin.import_tasks: tasks/zsh-ubuntu.yml
  when: ansible_os_family == 'Debian'

- name: Zsh | Run Task/s
  ansible.builtin.import_tasks: tasks/oh-my-zsh.yml
  when: ansible_os_family == 'Debian'

- name: Zsh | Run Task/s
  ansible.builtin.import_tasks: tasks/p10k.yml
  when: ansible_os_family == 'Debian'