---

- name: Zsh | Install zsh-syntax-highlighting
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-syntax-highlighting.git'
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"

- name: Zsh | zsh-auto-suggestions | Install
  ansible.builtin.git:
    repo: 'git clone https://github.com/zsh-users/zsh-autosuggestions'
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"