---
- name: Ensure themes directory exists
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/plugins"
    state: directory
    mode: '0755'
  become: true

- name: Zsh | Install zsh-syntax-highlighting
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-syntax-highlighting.git'
    dest: "{{ ansible_env.HOME }}/.config/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"
  become: true

- name: Zsh | zsh-auto-suggestions | Install
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-autosuggestions'
    dest: "{{ ansible_env.HOME }}/.config/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
  become: true