---
- name : nix-env | Install nix-env
  ansible.builtin.shell: |
    bash <(curl -L https://nixos.org/nix/install) --no-daemon
  args:
    executable: /bin/bash
  become: true

- name: check if nix-env is installed
  ansible.builtin.command: nix-env --version
  register: nix_env_version
  ignore_errors: true
  changed_when: false
