---
- name : nix-env | Install nix-env
  ansible.builtin.shell: |
    bash <(curl -L https://nixos.org/nix/install) --no-daemon
  args:
    executable: /bin/bash
  when: nix_env_check is not defined
  notify: nix-env | Source nix-env

  handlers:
    - name: nix-env | Source nix-env
      ansible.builtin.shell: |
        source /home/{{ ansible_user }}/.nix-profile/etc/profile.d/nix.sh
      args:
        executable: /bin/bash
      when: nix_env_check is not defined

- name: check if nix-env is installed
  ansible.builtin.command: nix-env --version
  register: nix_env_version
  ignore_errors: true
  changed_when: false

- name: set nix_env_check
  ansible.builtin.set_fact:
    nix_env_check: "{{ nix_env_version.rc == 0 }}"
