---

- name: "Git | Install git"
  ansible.builtin.apt:
    name:
      - git
    state: present
  become: true

- name: "Git | Configure git user email"
  ansible.builtin.command:
    cmd: git config --global user.email "23105954+Younis-Ahmed@users.noreply.github.com"

- name: "Git | Configure git user name"
  ansible.builtin.command:
    cmd: git config --global user.name "Younis Ahmed"