---

- name: Ensure nvim directory exists
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config/nvim"
    state: directory

- name: Ensure kickstart.nvim prerequisites are installed
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  become: true
  loop:
    - git
    - ripgrep
    - make
    - gcc
    - unzip

- name: Copy files to nvim config directory
  ansible.builtin.copy:
    src: "{{ role_path }}/files/"
    dest: "{{ ansible_env.HOME }}/.config/nvim/"
    remote_src: yes