---

- name: Download Nerd Fonts
  ansible.builtin.get_url:
    url: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/FiraCode.zip
    dest: "/tmp/FiraCode.zip"
    mode: '0440'

- name: Unzip
  ansible.builtin.package:
    name: unzip
    state: present
  become: true

- name: Unarchive Nerd Fonts
  ansible.builtin.unarchive:
    src: "/tmp/FiraCode.zip"
    dest: "/tmp"
    remote_src: yes

- name: Find font files
  ansible.builtin.shell: "find /tmp -name '*.otf'"
  register: font_files

- name: Zsh | Create fonts directory
  ansible.builtin.file:
    path: "/etc/fonts"
    state: directory
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: 0755
  become: true

- name: Install fontconfig
  ansible.builtin.package:
    name: fontconfig
    state: present
  become: true

- name: Update font cache
  ansible.builtin.command:
    cmd: fc-cache -fv
  become: true